import test from 'node:test';
import assert from 'node:assert/strict';
import {handleCart,safeCheckout} from '../src/lib/commerce/cart.server.ts';
const origin='https://preview.example.com';
const request=(body:unknown,headers:Record<string,string>={})=>new Request(origin+'/api/bag',{method:'POST',headers:{'content-type':'application/json',origin,...headers},body:JSON.stringify(body)});
test('checkout handoff rejects external and insecure destinations',()=>{assert.equal(safeCheckout('https://i6z1cd-5f.myshopify.com/checkouts/test'),'https://i6z1cd-5f.myshopify.com/checkouts/test');for(const url of ['https://evil.example/checkout','http://i6z1cd-5f.myshopify.com/cart','https://i6z1cd-5f.myshopify.com.evil.example','https://user@i6z1cd-5f.myshopify.com'])assert.throws(()=>safeCheckout(url));});
test('cross-origin cart mutations are rejected before Shopify is called',async()=>{const r=await handleCart(request({action:'reset'},{origin:'https://evil.example'}));assert.equal(r.status,403);assert.equal(r.headers.get('set-cookie'),null);});
test('bad quantities fail closed and never call commerce',async()=>{const old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('unexpected request');};try{const r=await handleCart(request({action:'add',variantId:'gid://shopify/ProductVariant/1',quantity:-1}));assert.equal(r.status,503);assert.equal(calls,0);}finally{globalThis.fetch=old;}});
test('cart reset expires only the essential cookie',async()=>{const r=await handleCart(request({action:'reset'}));assert.equal(r.status,200);assert.match(r.headers.get('set-cookie')!,/Max-Age=0/);assert.match(r.headers.get('set-cookie')!,/HttpOnly/);assert.match(r.headers.get('set-cookie')!,/Secure/);assert.deepEqual(await r.json(),{cart:null});});
test('successful cart creation uses GBP market context and secure cookie',async()=>{const old=globalThis.fetch;let sent:Record<string,any>={};globalThis.fetch=async(_url,init)=>{sent=JSON.parse(String(init?.body));return Response.json({data:{cartCreate:{cart:{id:'gid://shopify/Cart/test?key=private',checkoutUrl:'https://i6z1cd-5f.myshopify.com/checkouts/test',totalQuantity:1,lines:{nodes:[],pageInfo:{hasNextPage:false,endCursor:null}}},userErrors:[]}}});};try{const r=await handleCart(request({action:'add',variantId:'gid://shopify/ProductVariant/1',quantity:1}));assert.equal(r.status,200);assert.equal(sent.variables.input.buyerIdentity.countryCode,'GB');assert.match(r.headers.get('set-cookie')!,/HttpOnly; SameSite=Lax/);assert.match(r.headers.get('cache-control')!,/no-store/);}finally{globalThis.fetch=old;}});
test('Shopify user errors keep existing bag cookie and surface actionable error',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({data:{cartLinesAdd:{cart:null,userErrors:[{message:'This variant is unavailable.'}]}}});try{const r=await handleCart(request({action:'add',variantId:'gid://shopify/ProductVariant/1',quantity:1},{cookie:'ora_bag=existing'}));assert.equal(r.status,422);assert.equal(r.headers.get('set-cookie'),null);assert.match((await r.json()).error,/unavailable/);}finally{globalThis.fetch=old;}});

test('renamed Shopify checkout is allowed, lookalike domains are rejected',()=>{assert.equal(safeCheckout('https://natashathefounder.myshopify.com/checkouts/test'),'https://natashathefounder.myshopify.com/checkouts/test');assert.throws(()=>safeCheckout('https://natashathefounder.myshopify.com.evil.example/checkouts/test'));});

test('branded Shopify checkout host is supported',()=>{assert.equal(safeCheckout('https://ora.natashathefounder.com/checkouts/test'),'https://ora.natashathefounder.com/checkouts/test');assert.throws(()=>safeCheckout('https://ora.natashathefounder.com.evil.example/checkouts/test'));});

test('stack is sent as one mutation with all selected variants',async()=>{const old=globalThis.fetch;let calls=0;let sent:any;globalThis.fetch=async(_url,init)=>{calls++;sent=JSON.parse(String(init?.body));return Response.json({data:{cartCreate:{cart:{id:'gid://shopify/Cart/stack',checkoutUrl:'https://ora.natashathefounder.com/checkouts/test',totalQuantity:3},userErrors:[]}}});};try{const r=await handleCart(request({action:'addStack',lines:[{variantId:'gid://shopify/ProductVariant/1',quantity:1},{variantId:'gid://shopify/ProductVariant/2',quantity:2}]}));assert.equal(r.status,200);assert.equal(calls,1);assert.deepEqual(sent.variables.input.lines,[{merchandiseId:'gid://shopify/ProductVariant/1',quantity:1},{merchandiseId:'gid://shopify/ProductVariant/2',quantity:2}]);}finally{globalThis.fetch=old;}});
test('malformed stack is rejected before Shopify',async()=>{const old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('unexpected');};try{for(const lines of [[],[{variantId:'not-a-variant',quantity:1},{variantId:'gid://shopify/ProductVariant/2',quantity:1}]]){const r=await handleCart(request({action:'addStack',lines}));assert.equal(r.status,503);}assert.equal(calls,0);}finally{globalThis.fetch=old;}});
test('partially accepted Shopify cart remains accessible after an error',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({data:{cartCreate:{cart:{id:'gid://shopify/Cart/partial',checkoutUrl:'https://ora.natashathefounder.com/checkouts/test'},userErrors:[{message:'One charm is unavailable'}]}}});try{const r=await handleCart(request({action:'addStack',lines:[{variantId:'gid://shopify/ProductVariant/1',quantity:1},{variantId:'gid://shopify/ProductVariant/2',quantity:1}]}));assert.equal(r.status,422);assert.match(r.headers.get('set-cookie')!,/ora_bag=/);assert.match((await r.json()).error,/Check your bag/);}finally{globalThis.fetch=old;}});
